sylius_resource:
    resources:
        monsieurbiz_homepage.homepage:
            classes:
                model: MonsieurBiz\SyliusHomepagePlugin\Entity\Homepage\Homepage
                form: MonsieurBiz\SyliusHomepagePlugin\Form\Type\HomepageType
                repository: MonsieurBiz\SyliusHomepagePlugin\Repository\HomepageRepository
            translation:
                classes:
                    model: MonsieurBiz\SyliusHomepagePlugin\Entity\Homepage\HomepageTranslation

