services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false
        Sylius\Component\Resource\Model\ResourceInterface:
            autowire: false

#    MonsieurBiz\SyliusHomepagePlugin\Controller\:
#        resource: '../../Controller'
#        tags: ['controller.service_arguments']

    MonsieurBiz\SyliusHomepagePlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItem }


    # Homepage Forms
    MonsieurBiz\SyliusHomepagePlugin\Form\Type\HomepageType:
        arguments:
            - '%monsieurbiz_homepage.model.homepage.class%'

    MonsieurBiz\SyliusHomepagePlugin\Form\Type\HomepageTranslationType:
        arguments:
            - '%monsieurbiz_homepage.model.homepage_translation.class%'
