services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false

    MonsieurBiz\SyliusHomepagePlugin\:
        resource: '../../*'

    MonsieurBiz\SyliusHomepagePlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    # Menu item in admin panel
    MonsieurBiz\SyliusHomepagePlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItem }

    # Homepage Forms
    MonsieurBiz\SyliusHomepagePlugin\Form\Type\HomepageType:
        arguments:
            - '%monsieurbiz_homepage.model.homepage.class%'

    MonsieurBiz\SyliusHomepagePlugin\Form\Type\HomepageTranslationType:
        arguments:
            - '%monsieurbiz_homepage.model.homepage_translation.class%'

    # Fixtures
    MonsieurBiz\SyliusHomepagePlugin\Fixture\HomepageFixture:
        arguments:
            $exampleFactory: '@MonsieurBiz\SyliusHomepagePlugin\Fixture\Factory\HomepageFixtureFactory'

