monsieurbiz_sylius_homepage_shop_partial_view:
    path: /homepage
    methods: [GET]
    defaults:
        _controller: monsieurbiz_homepage.controller.homepage:indexAction
        _sylius:
            template: $template
            repository:
                method: findOneByChannelAndLocale
                arguments:
                    - "expr:service('sylius.context.channel').getChannel()"
                    - "expr:service('sylius.context.locale').getLocaleCode()"
